In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
b = np.array([2.4, -1.6, 9.2, 4.8, 3.76])

In [4]:
# floor , ceil, round
# floor: to previous whole number
np.floor(b)

array([ 2., -2.,  9.,  4.,  3.])

In [5]:
# ceil : ceiling, to next heighest whole nole number
np.ceil(b)

array([ 3., -1., 10.,  5.,  4.])

In [6]:
# around: rounding off
np.around(b)

array([ 2., -2.,  9.,  5.,  4.])

# Statistical Functions


In [7]:
#Alongwith min,max,amax,argmin,argmax,cumsum, we have a few more statistical functions

In [8]:
# amin & amax to calculate the max & min along an axis

In [9]:
c = np.array([[2, 4, 8, 12, 6],[7, 2, 34, 1, 9],[3, 5, 7, 1, 67]])
c.shape

(3, 5)

In [10]:
c.size

15

In [11]:
c.itemsize

4

In [15]:
#the smallest number through the array across all axis
np.min(c)

1

In [17]:
#the smallest number through the array across all axis
np.amin(c)

1

In [2]:
 import numpy as np

a = np.array([
[3,5,7,9,2,4,6],
[4,2,7,5,9,4,0],
[6,1,6,8,9,3,5],
[7,3,8,0,2,3,5]
])

In [3]:
np.amin(a,0)

array([3, 1, 6, 0, 2, 3, 0])

In [4]:
np.amin(a,1)

array([2, 0, 1, 0])

In [19]:
# min along axis-0 or rows;
np.amin(c,0)


array([2, 2, 7, 1, 6])

In [20]:
# min along axis-1 or columns;
np.amin(c,1)

array([2, 1, 1])

In [6]:
#percentile
#the second parameter is called q, q-th percentile gives a value below which q percentage of the values fall.
# here 1.4 percentile of the elements fall below 10% of the population
c = np.array([[2, 4, 8, 12, 6],[7, 2, 34, 1, 9],[3, 5, 7, 1, 67]])

# elements = 15
# smallest = 1 (freq =2); second lowest = 2 (freq=2)
np.percentile(c,10)

1.4000000000000001

In [9]:
np.percentile(c, 20)

2.0

In [25]:
np.percentile(c, 40)

4.6000000000000005

In [26]:
#CENTRAL TENDENCIES

In [27]:
#Mean of the array
np.mean(c)

11.2

In [28]:
#mean of the array across axis-0
np.mean(c,0)

array([ 4.        ,  3.66666667, 16.33333333,  4.66666667, 27.33333333])

In [29]:
#mean across axis-> 1
np.mean(c, 1)

array([ 6.4, 10.6, 16.6])

In [32]:
#median across the array
np.median(c)

6.0

In [33]:
#median across axis 0
np.median(c, 0)

array([3., 4., 8., 1., 9.])

In [34]:
#average
np.average(c)

11.2

In [13]:
#returns only unique items from the array, sorted
# sort & duplicates removal, dimenisons to 1d
np.unique(c)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 34, 67])

In [10]:
d = np.array([[9,23,2,1,5],[1,9,2,4,6],[3,0,5,2,1]])
print(d)
print()
print(np.unique(d))

[[ 9 23  2  1  5]
 [ 1  9  2  4  6]
 [ 3  0  5  2  1]]

[ 0  1  2  3  4  5  6  9 23]


In [36]:
d = np.array([4, 3, 9, 4, 2, 7, 2, 8, 10, 6, 8, 3])
np.unique(d)

array([ 2,  3,  4,  6,  7,  8,  9, 10])

In [41]:
e = np.random.randint(14,28,8)
e

array([15, 18, 23, 23, 16, 22, 22, 15])

In [45]:
#creates a histogram distribution for the range
np.histogram(e)

(array([2, 1, 0, 1, 0, 0, 0, 0, 2, 2], dtype=int64),
 array([15. , 15.8, 16.6, 17.4, 18.2, 19. , 19.8, 20.6, 21.4, 22.2, 23. ]))

In [50]:
# creates histogram range, with the number of ranges = bins declared; alongwith the frequency
np.histogram(e, bins=5)

(array([3, 1, 0, 0, 4], dtype=int64),
 array([15. , 16.6, 18.2, 19.8, 21.4, 23. ]))

In [51]:
np.histogram(e, bins=8)

(array([2, 1, 0, 1, 0, 0, 0, 4], dtype=int64),
 array([15., 16., 17., 18., 19., 20., 21., 22., 23.]))

In [53]:
#flatten function to flatten a multidimensional array to 1d array
c = np.array([[2, 4, 8, 12, 6],[7, 2, 34, 1, 9],[3, 5, 7, 1, 67]])
f = c.flatten()
f

array([ 2,  4,  8, 12,  6,  7,  2, 34,  1,  9,  3,  5,  7,  1, 67])

In [54]:
# std -> standard deviation in a set of data
np.std(f)

16.825377657970513

In [55]:
np.std(a)

2.8722813232690143

In [56]:
np.mean(a)

4.5

In [11]:
e = np.random.randint(20,35,10)
e

array([26, 31, 25, 24, 34, 31, 22, 25, 21, 24])

In [12]:
np.histogram(e)

(array([2, 0, 2, 3, 0, 0, 0, 2, 0, 1], dtype=int64),
 array([21. , 22.3, 23.6, 24.9, 26.2, 27.5, 28.8, 30.1, 31.4, 32.7, 34. ]))