In [1]:
#Array slicing uses the same logic as list slicing

#Let's create an array
import numpy as np
a = np.arange(1,10)

In [2]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#The shape of the array
a.shape

(9,)

In [4]:
#Total number of elements in the array
a.size

9

In [5]:
# The indexing starts from 0
# slicing can be done using :

a[0:3]

array([1, 2, 3])

In [6]:
# It uses three arguements [start:end:step]
# suppose you wish to start from the 1st element you use index 0, you can slice like
# array[start:stop]
a[0:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#if not sure about the elements count, you might leave the stop element as blank
a[0:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#if feeling lazy, you might skip the start start element
a[:5]

array([1, 2, 3, 4, 5])

In [9]:
# and you might even skip the start & stop element to start from 0 and stop at the final element
a[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#now we need to understand the final arguement, the steps; which is similar to list
#start from the 1st count, and to the end
a[0:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#lets add steps, suppose we wish to skip the alternate elements, we might a step count of 2
a[0:10:2]

array([1, 3, 5, 7, 9])

In [12]:
#lets add steps, suppose we wish to skip the alternate elements, we might a step count of 3
a[0:10:3]

array([1, 4, 7])

In [13]:
#lets add steps, suppose we wish to skip the alternate elements, we might a step count of 4
a[0:10:4]

array([1, 5, 9])